### ISSUE TITLE
How to reach you?

### ISSUE THREAD

**Issue by V1TA5** [c3nav/c3nav#10]
Hi,
i spoke to the assembly orga and they told me their wish to extend the c3nav to allow them to directly manage their assembly planing with it (and have realtime edit functions). I agreed to bring everyone together to talk about this. You can find me on irc hackint as "VITAS".

**Comment by nomoketo** [comment]
Hi, 

i'm already in contact with the Assembly orga and their wishes are known to me :) You can contact me everywhere as nomoketo and using the mail and xmpp adresses that can be found on my website and github profile. XMPP: nomoketo@nomoketo.de and nomoketo in hackint
