### ISSUE TITLE
Group filter on API spaces endpoint not working

### ISSUE THREAD

**Issue by keunes** [c3nav/c3nav#123]
Hello,

With FOSDEM we're using c3nav with great appreciation.

In preparation of instructions for the cleaning crew, I would like to pull a list of all Toilets on the campus. If I understand the info on the `spaces` endpoint correctly, it should be possible to filter by group ID. In our case `562` for toilets:
https://nav.fosdem.org/api/spaces/?group=562

However, when applying this filter in the URL, the returned list doesn't filter by group.

I'm not entirely sure which 'version' (commit) we're on, so it might be that this has already been addressed with the recent changes. If not, it'd be great if this could be fixed.

Many thanks for your work and good luck with C3 preparations!

**Comment by codingcatgirl** [comment]
Hey. This question is kinda obsolete right now since since a few days there's `/api/v2/`. Can you check if the bug exists there as well?

What you are doing seems correct, so it looks like it might be a bug, but i would hope that it doesn't exist in the new API.

**Comment by keunes** [comment]
Thanks for the quick reply. Then I guess we're indeed not at the most recent version/commit. I've asked internally if we can upgrade and will test once that's done.

**Comment by codingcatgirl** [comment]
Now is a good time to upgrade since we are actively developing on it, so if you run into any issues we are familiar with the codebase :)

**Comment by gwenya** [comment]
This seems to be working with the new API, feel free to reopen if you find it is still an issue.

**Comment by keunes** [comment]
We wouldn't be able to reopen because a project owner closed it, but I trust you're right :-)

We're still looking into upgrading, but due to some other changes already taking up time of the team, it looks like it'll be for next year.

Thanks again!
