### ISSUE TITLE
Conversion rule for room name mappings / new guid redirect

### ISSUE THREAD

**Issue by johnjohndoe** [c3nav/c3nav#124]
# Context
Room names used in an event schedule (e.g. [36c3](https://github.com/voc/36c3_schedule)) are mapped to room names used with c3nav.
Excerpt from https://github.com/c3nav/c3nav/blob/main/res/mappings.36c3.json:

``` json
{
  "Ada": "hall-a",
  "Borg": "hall-b",
  "Clarke": "hall-c",
  "Dijkstra": "hall-d",
  "Eliza": "hall-e",
  "Art-and-Play Installation": "artandplay",
  "Art-and-Play Stage": "ap-stage",
  "Assembly:Anarchist Village": "anarchist-assembly",
  // ...
}
```

# Proposal
It would be convenient if a **conversion rule** (regex, ...) to programmatically **generate** room names can be used. Once such a rule is in place and shared clients such as the 3xc3 Schedule app for Android/iOS, Giggity can **rely on the mapping function** to correctly link to c3nav URLs from within the Android app.

# Related
- [EventFahrplan//RoomForC3NavConverter](https://github.com/EventFahrplan/EventFahrplan/blob/master/app/src/main/java/nerd/tuxmobil/fahrplan/congress/navigation/RoomForC3NavConverter.kt)
- #30 
- #43 
- #47 
- #48 

---

fyi: @Wilm0r, @toto

**Comment by codingcatgirl** [comment]
Hm. That is unlikely to ever happen since how slugs are determined is determined based on many design decisions based on the specifics of the location.

However, a much simpler solution might be if we simply offered a way to use the pretalx room ID or something to link to a location? It could simply generate a redirect to the actual link then.

**Comment by johnjohndoe** [comment]
Thank you for the suggestion. I can see that in the [37C3 `schedule.xml`](https://fahrplan.events.ccc.de/congress/2023/fahrplan/schedule.xml) each `room` has a `guid`:

``` xml
<room name="House" guid="a27fcab0-d25f-466a-968d-0e86df84aa79">
```

The EventFahrplan app could parse this field - it does not do so yet.

I hereby like to ask @saerdnaer if there is any reason not to go with this solution?!

---

With regards to the slug - could you please explain how the specifics of the location influence the choice for names?

**Comment by johnjohndoe** [comment]
@saerdnaer Will the `guid` field be a mandatory or optional field (in the schema definition)? I noticed that there is not `guid` for the `room` node in the [36C3 `schedule.xml`](https://github.com/voc/36c3_schedule).

**Comment by johnjohndoe** [comment]
@codingcatgirl Is/will the following URL be correct to address the `House` room?

https://37c3.c3nav.de/l/a27fcab0-d25f-466a-968d-0e86df84aa79

**Comment by codingcatgirl** [comment]
I think we'll just set up the uuids as redirecting slugs so, yep. This is how you'd link to a UUID.

**Comment by johnjohndoe** [comment]
Okay. Thank you. So, I will add and enable this addressing scheme for the 37C3 Schedule app. Thank you for this nice improvement.

**Comment by johnjohndoe** [comment]
:heavy_check_mark: The EventFahrplan / 37C3 app is now prepared to use the room `guid` attribute to generate a c3nav URL. See: https://github.com/EventFahrplan/EventFahrplan/pull/583

**Comment by se4598** [comment]
great!
i will create a todo on our board to add the GUIDs of the rooms as redirecting slugs.
