### ISSUE TITLE
editor: stuck in "mobileclient not found"

### ISSUE THREAD

**Issue by se4598** [c3nav/c3nav#126]
Given I'm logged in and start on https://37c3.c3nav.de/editor/ with the editor overview.
When I click on "Way Types" (or any other entry) and then click on "back to overview" then I only see
> **c3nav map editor**
> mobileclient not found. Please install the c3nav app for wifi scanning support."
and not the normal editor overview

![grafik](https://github.com/c3nav/c3nav/assets/1153763/23eafbd2-1144-46b3-8707-6edbb4405d9e)

if I click on the logo I still see the same screen/nothing changes.

(Firefox; bug not always reliable reproduceable, sometimes it "just works" as one would expect)

**Comment by gwenya** [comment]
I thought I had fixed that already, hm, I’ll try to look into it again tomorrow
