### ISSUE TITLE
http 500 when trying to view changeset #40

### ISSUE THREAD

**Issue by se4598** [c3nav/c3nav#130]
https://37c3.c3nav.de/editor/changesets/40/ -> Server Error (500)
(happened after accepting and applying, seems to be applied)

**Comment by se4598** [comment]
another instance, but here still in editing mode/open changeset: https://37c3.c3nav.de/editor/changesets/46/

**Comment by gwenya** [comment]
I pushed a fix for one of the possible causes of this, idk if it’s deployed yet 
If it’s still broken tomorrow can you let me know?
