### ISSUE TITLE
embedded view: "undefined" in marker tooltip

### ISSUE THREAD

**Issue by se4598** [c3nav/c3nav#136]
on https://37c3.c3nav.de/embed/l/press-room

clicking on the marker shows a "undefined" in the tooltip

![grafik](https://github.com/c3nav/c3nav/assets/1153763/009714cc-eb39-4121-bf2d-6f6e3a521344)

**Comment by gwenya** [comment]
Usually the buttons go there, but that doesn't make sense in the embed, I think. Should there just be nothing below the title+subtitle, or something else? @codingcatgirl
