### ISSUE TITLE
Set a default starting location for navigation

### ISSUE THREAD

**Issue by benedikt-haug** [c3nav/c3nav#156]
IMHO there should be a default starting location for the navigation feature. Most people that would need navigation don't know the room number they are currently in.

Ideally query the actual location, but if that's not possible I'd suggest using the food trucks as default starting location given that almost everyone knows the food trucks location and how they got to their current room from there.

**Comment by codingcatgirl** [comment]
I assume this is a suggestion for FOSDEM, since the point about the food trucks doesn't make sense for any of the instances we run. 

c3nav is free open source software that anyone can run. Not every instance of it is run by us.
