### ISSUE TITLE
Create locationgroups that can be selected for missing locations, but then give an error message

### ISSUE THREAD

**Issue by codingcatgirl** [c3nav/c3nav#167]
This is needed in case people feel like reporting missing assemblies when in fact we don't accept these.

**Comment by se4598** [comment]
like last c3, to redirect people to a more appropriate channel, outside of c3nav?

**Comment by codingcatgirl** [comment]
Yes.

**Comment by codingcatgirl** [comment]
Implemented with report functionality overhaul.
