### ISSUE TITLE
broken navigation from infodesk to NGI assembly

### ISSUE THREAD

**Issue by hirnsalat** [c3nav/c3nav#19]
Apparently, the route from Infodesk to NGI involves going to CCL and teleporting from there.

![screenshot](https://user-images.githubusercontent.com/242447/34420299-1dd13264-ec09-11e7-84ed-38d2324f33cc.png)

**Comment by codingcatgirl** [comment]
This was caused by the assembly being put inside the wrong space (but still in the right position). It's not a bug in c3nav but in the data entered by the assembly team. Anyway, now it's to late to fix it because the 34c3 is over.
