### ISSUE TITLE
Exception 'got a string in GeometryField.to_python()' when using manage.py loaddata

### ISSUE THREAD

**Issue by danielegobbetti** [c3nav/c3nav#193]
Hello,

I am helping setting up a c3nav instance for an upcoming conference, some mapping work has been done on a development instance (local development using sqlite as database) and its contents have been exported using ``python manage.py dumpdata mapdata``.
The command run without giving errors.

When loading the data in the testing instance (docker development, git hash 897cf68ccc1731372ee3fba6044b6292f7bdc3d3, using postgres as database) the exception mentioned in the subject is being raised:
```
  File "/app/c3nav/mapdata/fields.py", line 61, in to_python
    raise ValueError('got a string in GeometryField.to_python()')
ValueError: Problem installing fixture '-': got a string in GeometryField.to_python()
```

I tried exporting to json and xml, the error does not change. The error is reproducible also in the local development installation.

I've noticed this was changed in https://github.com/c3nav/c3nav/commit/6eaf087f71718fd6c3ae6cdf27fab7435b679470#diff-cb10ab34b037523bb710b25a03a52faec3512e4212fae9f2a5e5dabecf58d512 .

I've tested locally reverting the change to lines 59-60 to:
```
            value = json.loads(value)
```
as it was before the referenced commit, and the loaddata command runs without issues.

**Comment by codingcatgirl** [comment]
This is fixed on a dev branch presently, but as mentioned in another comment, loaddata/dumpdata is currently not supported anyways.
