### ISSUE TITLE
Make grid (and other) configuration available via API

### ISSUE THREAD

**Issue by skruppy** [c3nav/c3nav#201]
Right now, the grid configuration ("rows", "cols", "invert_x" and "invert_y") is only available as the "data-grid" attribute of a div in the main view.

It would be nice to have this configuration available at an API endpoint.

Maybe a generic "config" endpoint would be a good location for such data, since also other things like the tiles server URL or the initial level/bounds are also only accessible in HTML attributes.

**Comment by codingcatgirl** [comment]
Thanks, we'll aim to implement this until congress. How urgently do you need it?

**Comment by skruppy** [comment]
Sorry for the late reply. You implemented it faster than I could answer :). Thank you :heart: !
