### ISSUE TITLE
[Request] New documentation

### ISSUE THREAD

**Issue by ShinIce** [c3nav/c3nav#21]
Hi there :)

Do you have any idea when the documentation for the new app will be available?
Time is getting short for the next FOSDEM and I would be happy if we can get the new nav up and running in time ;)

You did really an awesome work 👍 🍻 

Thanks

**Comment by codingcatgirl** [comment]
Due to [the recent events at the 34c3](https://twitter.com/c3nav/status/946453633864003584), my motivation to work on c3nav is currently very low. But i'll do my best.

**Comment by exmatrikulator** [comment]
@ShinIce https://nav.fosdem.org is working, so you did it!
congratulations!

do you have source / documentation whats running there?
https://github.com/FOSDEM/navigation is sadly empty.

Thanks!

**Comment by codingcatgirl** [comment]
Fosdem got help from me. The c3nav project is not dead, we are just currently not working on it much. I'll contact you privately.

**Comment by johanvdw** [comment]
@exmatrikulator : you can find our setup here: https://github.com/FOSDEM/infrastructure/tree/master/ansible/playbooks/roles/ (maps and maps tileserver roles).
We run master except for a patch you should avoid using (I should look again if we can get rid of it).
