### ISSUE TITLE
Provide map data for CCL and 34C3

### ISSUE THREAD

**Issue by petabyteboy** [c3nav/c3nav#22]
Hello,

first of all thanks for your amazing work and this awesome project. 
I want to play with c3nav and hack it, but I can't find any data set for the latest version.
Can you provide the maps for 34C3?

Thanks in advance

PetaByteBoy // Milan

**Comment by codingcatgirl** [comment]
The data set is currently not public, publishing it is not so ease and we are currently not planning work on anything chaos communication congress related any time soon. sorry.
