### ISSUE TITLE
[BUG/SDK] crashes the launcher and Settings-Apps

### ISSUE THREAD

**Issue by alsternerd** [c3nav/c3nav#23]
General information

    App version: Latest
    App source: F-Droid
    Android Version: 6.0.1
    Custom ROM: KonstaKANG LineageOS

Expected result

What is expected?
The app installs/upgrades without crashes parts of the system or the whole system.

What does happen instead?
It crashes the App-Launcher and Settings -> Apps Menu.
No uninstallation possible without ADB-access.
Steps to reproduce

    Install latest version.

I got this same issue with mastalab, but without crashing the launcher, it could be the same root here:

The problems are the Android SDK Platform 25 and 26, with 27 (revision: 1) it should work like a charm.

Sources:
stom79/mastalab#31
https://github.com/andOTP/andOTP/issues/76

What helped us figuring this out: https://forums.bitfire.at/topic/1603/replicant-lineage-1-9-1-causing-instant-crash-and-bootloops/15

**Comment by codingcatgirl** [comment]
Yeah, um, this is the repo of the c3nav website / backend, not of the app. You might want to report this to [c3nav/c3nav-android](https://github.com/c3nav/c3nav-android), i guess?
