### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by johanvdw** [c3nav/c3nav#28]
I noticed in commit https://github.com/c3nav/c3nav/commit/c5fc590c2af12d7eaf6b11358236f2a367865e41 the default Python version was changed to 3.7.

Would it be possible to keep supporting also 3.6? Most linux distributions are still stuck at versions before 3.7 and using the latest version makes the deployment more complicated.

**Comment by evilscientress** [comment]
Python 3.6 is still completely supported, and we use it our self on the production system. 
Travis is currently work in progress and non functional, because of their VMs don't offer the opengl libs we need.
I also added python 3.6 back to the travis config in e059d3a9, to avoid confusion.
