### ISSUE TITLE
Implement deeplinking in C3 fahrplan

### ISSUE THREAD

**Issue by pelim** [c3nav/c3nav#31]
Please implement deeplinking in fahrplan / web / android  by state of the art technology

It sucks to switch between two apps

**Comment by codingcatgirl** [comment]
You should probably report this the c3 fahrplan app, not here.

**Comment by johnjohndoe** [comment]
The 36C3 is emitting an intent with the same parameterized URL which you would type into your browser to open the c3nav website. See https://github.com/EventFahrplan/EventFahrplan/blob/master/app/src/main/java/nerd/tuxmobil/fahrplan/congress/details/EventDetailFragment.java, onOptionsItemSelected

**Comment by codingcatgirl** [comment]
…and that intent is also correctly catched by the c3nav app if you have it installed. So yeah, i'm not even sure what this issue is about? When this issue was opened this was the case already afaik.

**Comment by johnjohndoe** [comment]
I agree. Maybe @pelim wants to clarify the issue.
