### ISSUE TITLE
copying spaces across levels

### ISSUE THREAD

**Issue by johanvdw** [c3nav/c3nav#33]
I might be doing things wrong, but I'm looking for an easy way to copy a space between levels, eg for an elevator. Is there a way to do this (rather than use sql to update the geometry, which I did).

**Comment by codingcatgirl** [comment]
Currently there is no easy way to do that. Although using the Django Console instead of SQL is probably a bit easier ^^

**Comment by codingcatgirl** [comment]
FYI, we just added a bulk edit feature (which allows you to move geometry between spaces or levels) and a clone feature. So you can practically do this now :)
