### ISSUE TITLE
[Request] Increase accuracy of c3nav with dynamic updates to access point

### ISSUE THREAD

**Issue by Phil5555** [c3nav/c3nav#51]
Please deploy (lots of) Wifi scanners (ESP32, ESP8266) with fixed, known locations to provide c3nav internal Wifi database with continuous updates. This would (hopefully) increase accuracy of c3nav locating API during heavily changing WiFi conditions. (Congress and similar events)

**Comment by codingcatgirl** [comment]
Thanks, do you want us to just drop a paypal link so you can pay for it, or…?

**Comment by evilscientress** [comment]
We are working on improving the indoor navigation. ESP32, and ESP8266 are not usable because they can't handle the large number of APs. Where a scan with an laptop or smart phone shows 70+ APs the ESP would only show 3-5. Also the ESP8266 doesn't support 5GHz.
