### ISSUE TITLE
Embedding in engelsystem does not work

### ISSUE THREAD

**Issue by rugk** [c3nav/c3nav#54]
### STR

Go to https://engelsystem.de/36c3/rooms?action=view&room_id=23

### What happens

Looks like this:
![grafik](https://user-images.githubusercontent.com/11966684/71558468-0a7ff980-2a54-11ea-9767-f09ee7d64fd9.png)

### What should happen

Should display a marker, possibly?

## Also

* the "open in c3nav" link was a text (text cursor); when I dragged the map, it became a link)
* if I click that link through, it also just opens https://36c3.c3nav.de/@0,589.29,214.76,-0.46 i.e. a usual website

## System

Firefox 71
Fedora 31
GNOME

---

copied from/originally reported at https://github.com/engelsystem/engelsystem/issues/711

See this issue there also for more details! (TL;DR: seems to be some cookie/localstorage problem, maybe?)

I do have third-party cookies disabled.

**Comment by codingcatgirl** [comment]
Thanks for reporting this! Looks indeed like a localstorage problem that crashes our code.
