### ISSUE TITLE
underscores in slugs

### ISSUE THREAD

**Issue by johanvdw** [c3nav/c3nav#56]
Hello,

For FOSDEM, we have mapped a large number of rooms with slugs containing underscores. This also matches the slugs used in our scheduling system which contain underscores as well.

Is there a technical reason underscores are not supported, or is it just a matter of styling? Ie, if we disable the check, would it break in unexpected ways?

**Comment by codingcatgirl** [comment]
Can't say it for sure off the top of my head, but if the restriction just comes from the django-slug-field, then there should be no technical reason. Personally, i think underscores in URLs are a bad style, but that's definitely a matter of taste.
