### ISSUE TITLE
Saving settings in Cookie not working

### ISSUE THREAD

**Issue by lastfuture** [c3nav/c3nav#6]
on iOS c3nav doesn't save settings in a cookie

steps I took: add c3nav as bookmark to the home screen, navigate from Zwischenfoyer Saal 2 to Lounge, change elevators to avoid (checkbox to save in cookie is set), recalc route.

Expected: elevators remain set to avoid for the next route
Actual behavior: all settings reverted to default allow

**Comment by nomoketo** [comment]
are you sure those two things happened in the same browser?

**Comment by codingcatgirl** [comment]
reimplemented anyway in new version
