### ISSUE TITLE
How to use redirecting slugs

### ISSUE THREAD

**Issue by johanvdw** [c3nav/c3nav#60]
I'm trying to understand how to use the redirecting slugs. For FOSDEM we have a room for which k1105 is the slug, and I would like to add k1105_la_fontaine as a redirecting slug, as this is what our program uses for [this room](https://fosdem.org/2020/schedule/room/k1105_la_fontaine/).
I have added it under redirecting slug, but I only seem to get the original working:
https://nav.fosdem.org/l/k1105
I thought something like https://nav.fosdem.org/l/k1105_la_fontaine should also work, but it does not. How are we supposed to use these redirecting slugs?

**Comment by codingcatgirl** [comment]
Thank you for reporting this issue, i just fixed the underlying problem in the master branch.

**Comment by johanvdw** [comment]
Cool, thanks!
