### ISSUE TITLE
Provide JSON Routing API

### ISSUE THREAD

**Issue by friesenkiwi** [c3nav/c3nav#7]
Hey! It would be very cool, if there was a simple routing API which I could use as a backend for the Mixare Augmented Reality Navigation App (https://github.com/pokerazor/mixare). Currently it only works outdoor with a custom OSM routing backend in one level, but I think, I may be able to extend it to multi-level indoor routing. I'm currently at the congress, so if you're interested, we could meet up and discuss possibilities, I could show you how the app currently works.

**Comment by nomoketo** [comment]
Hi. I actually anticipated this and the software is more or less ready to provide an API. if everything goes well, i will add it tomorrow or even tonight :)

**Comment by friesenkiwi** [comment]
Ok, cool!
Currently, the app uses a URL like this:
https://cloud.locoslab.com/carta/route?mode=walking&origin=53.5631,9.9850&destination=53.5618,9.9878
it outputs
a JSON like this:
`{"routes":[{"duration":202,"targetCoordinate":{"latitude":53.5618,"longitude":9.9878},"distance":280.51287255819034,"sourceCoordinate":{"latitude":53.5631,"longitude":9.985},"sourceLevel":0,"steps":[{"distance":280.51287255819034,"coordinates":"knfdeBc{l`RkC~BwG~B??dBaK~DwM??Vi@rBaG`^st@bHwMrk@wdA","starttime":4663,"stoptime":4865,"type":1,"segments":[{"duration":18,"road":"Tiergartenstraße","coordinates":"knfdeBc{l`RkC~BwG~B","turn":0,"type":6},{"duration":24,"road":"Tiergartenstraße","coordinates":"o{fdeBcsl`RdBaK~DwM","turn":8,"type":6},{"duration":160,"road":"Tiergartenstraße","coordinates":"irfdeB}mm`RVi@rBaG`^st@bHwMrk@wdA","turn":1,"type":16}]}],"targetLevel":0}]}`

but an easier format should be possible...

**Comment by nomoketo** [comment]
Not yet in the nice API preview, but you can for now add ?format=json to your routing request and get JSON output instead of HTML.
