### ISSUE TITLE
Switching locations on "show route" screen does not actually change locations

### ISSUE THREAD

**Issue by xpac1985** [c3nav/c3nav#8]
Short video documentation of issue:
https://youtu.be/Z77pX_0ZVxA

In short - it seems to switch the locations for the route screen, but when calculating the route, they switch back.
Windows 8.1 (updated)
Chrome 55.0.2883.87 (64bit)
Multiple extensions including ublock origin and others

Can be reproduced everytime I tried, same issue on my Android with Chrome browser

**Comment by codingcatgirl** [comment]
fixed in the newly implemented UI
